#include <cstdint>

#include "include/touhou_native/abi.h"
#include "include/touhou_native/export.hpp"
#include "src/internal/abi_impl.hpp"


TOUHOU_EXPORT int touhou_clearance_volume_v1(
    float x_start,
    float x_step,
    int column_count,
    float y_start,
    float y_step,
    int row_count,
    int frame_count,
    float player_radius,
    float clearance_cap,
    const float* aabb_x,
    const float* aabb_y,
    const float* aabb_velocity_x,
    const float* aabb_velocity_y,
    const float* aabb_half_width,
    const float* aabb_half_height,
    const float* aabb_base_uncertainty,
    const float* aabb_uncertainty_per_frame,
    int aabb_count,
    const float* segment_origin_x,
    const float* segment_origin_y,
    const float* segment_angle,
    const float* segment_tail,
    const float* segment_head,
    const float* segment_half_width,
    const float* segment_base_uncertainty,
    const float* segment_uncertainty_per_frame,
    int segment_count,
    float* output
) {
    return touhou_native_impl_clearance_volume_v1(
        x_start,
        x_step,
        column_count,
        y_start,
        y_step,
        row_count,
        frame_count,
        player_radius,
        clearance_cap,
        aabb_x,
        aabb_y,
        aabb_velocity_x,
        aabb_velocity_y,
        aabb_half_width,
        aabb_half_height,
        aabb_base_uncertainty,
        aabb_uncertainty_per_frame,
        aabb_count,
        segment_origin_x,
        segment_origin_y,
        segment_angle,
        segment_tail,
        segment_head,
        segment_half_width,
        segment_base_uncertainty,
        segment_uncertainty_per_frame,
        segment_count,
        output
    );
}

TOUHOU_EXPORT int touhou_segment_trajectory_clearance_v1(
    float x_start,
    float x_step,
    int column_count,
    float y_start,
    float y_step,
    int row_count,
    int frame_count,
    float player_radius,
    const std::int32_t* frame_offsets,
    const float* segment_origin_x,
    const float* segment_origin_y,
    const float* segment_angle,
    const float* segment_tail,
    const float* segment_head,
    const float* segment_half_width,
    const float* segment_base_uncertainty,
    const float* segment_uncertainty_per_frame,
    int segment_sample_count,
    float* inout
) {
    return touhou_native_impl_segment_trajectory_clearance_v1(
        x_start,
        x_step,
        column_count,
        y_start,
        y_step,
        row_count,
        frame_count,
        player_radius,
        frame_offsets,
        segment_origin_x,
        segment_origin_y,
        segment_angle,
        segment_tail,
        segment_head,
        segment_half_width,
        segment_base_uncertainty,
        segment_uncertainty_per_frame,
        segment_sample_count,
        inout
    );
}

TOUHOU_EXPORT int touhou_aabb_trajectory_clearance_v1(
    float x_start,
    float x_step,
    int column_count,
    float y_start,
    float y_step,
    int row_count,
    int frame_count,
    float player_radius,
    const std::int32_t* frame_offsets,
    const float* aabb_x,
    const float* aabb_y,
    const float* aabb_half_width,
    const float* aabb_half_height,
    const float* aabb_base_uncertainty,
    const float* aabb_uncertainty_per_frame,
    int aabb_sample_count,
    float* inout
) {
    return touhou_native_impl_aabb_trajectory_clearance_v1(
        x_start,
        x_step,
        column_count,
        y_start,
        y_step,
        row_count,
        frame_count,
        player_radius,
        frame_offsets,
        aabb_x,
        aabb_y,
        aabb_half_width,
        aabb_half_height,
        aabb_base_uncertainty,
        aabb_uncertainty_per_frame,
        aabb_sample_count,
        inout
    );
}

TOUHOU_EXPORT int touhou_annular_sector_trajectory_clearance_v1(
    float x_start,
    float x_step,
    int column_count,
    float y_start,
    float y_step,
    int row_count,
    int frame_count,
    float player_radius,
    const std::int32_t* frame_offsets,
    const double* origin_x,
    const double* origin_y,
    const double* minimum_angle,
    const double* maximum_angle,
    const double* minimum_radius,
    const double* maximum_radius,
    const double* half_extent_radius,
    const double* origin_uncertainty,
    const double* base_uncertainty,
    const double* uncertainty_per_frame,
    int sample_count,
    float* inout
) {
    return touhou_native_impl_annular_sector_trajectory_clearance_v1(
        x_start,
        x_step,
        column_count,
        y_start,
        y_step,
        row_count,
        frame_count,
        player_radius,
        frame_offsets,
        origin_x,
        origin_y,
        minimum_angle,
        maximum_angle,
        minimum_radius,
        maximum_radius,
        half_extent_radius,
        origin_uncertainty,
        base_uncertainty,
        uncertainty_per_frame,
        sample_count,
        inout
    );
}

TOUHOU_EXPORT int touhou_annular_sector_frame_clearance_v1(
    const float* positions_x,
    const float* positions_y,
    int position_count,
    int frame,
    float player_radius,
    const double* origin_x,
    const double* origin_y,
    const double* minimum_angle,
    const double* maximum_angle,
    const double* minimum_radius,
    const double* maximum_radius,
    const double* half_extent_radius,
    const double* origin_uncertainty,
    const double* base_uncertainty,
    const double* uncertainty_per_frame,
    int sample_count,
    float* output
) {
    return touhou_native_impl_annular_sector_frame_clearance_v1(
        positions_x,
        positions_y,
        position_count,
        frame,
        player_radius,
        origin_x,
        origin_y,
        minimum_angle,
        maximum_angle,
        minimum_radius,
        maximum_radius,
        half_extent_radius,
        origin_uncertainty,
        base_uncertainty,
        uncertainty_per_frame,
        sample_count,
        output
    );
}

TOUHOU_EXPORT int touhou_piecewise_aabb_clearance_v1(
    float x_start,
    float x_step,
    int column_count,
    float y_start,
    float y_step,
    int row_count,
    int frame_count,
    float player_radius,
    const double* aabb_x,
    const double* aabb_y,
    const double* aabb_velocity_x,
    const double* aabb_velocity_y,
    const float* aabb_half_width,
    const float* aabb_half_height,
    const float* aabb_base_uncertainty,
    const float* aabb_uncertainty_per_frame,
    int aabb_count,
    const std::int32_t* event_offsets,
    const std::int32_t* event_frames,
    const double* event_velocity_x,
    const double* event_velocity_y,
    int event_count,
    float* inout
) {
    return touhou_native_impl_piecewise_aabb_clearance_v1(
        x_start,
        x_step,
        column_count,
        y_start,
        y_step,
        row_count,
        frame_count,
        player_radius,
        aabb_x,
        aabb_y,
        aabb_velocity_x,
        aabb_velocity_y,
        aabb_half_width,
        aabb_half_height,
        aabb_base_uncertainty,
        aabb_uncertainty_per_frame,
        aabb_count,
        event_offsets,
        event_frames,
        event_velocity_x,
        event_velocity_y,
        event_count,
        inout
    );
}
