"""Game-neutral corridor planning components."""

from .adaptive_refinement import (
    QueryLocalDualBoundResult,
    QueryLocalRefinementPatch,
    build_query_local_refinement_patch,
    solve_query_local_dual_bounds,
    solve_query_local_dual_bounds_vectorized,
    trivial_coarse_action_bounds,
)
from .clearance import (
    aabb_clearance_field,
    aabb_clearance_volume,
    aabb_sample_clearance_field,
    annular_sector_clearance_field,
    packed_annular_sector_clearance_field,
    clearance_field,
    hazard_clearance_volume,
    packed_segment_clearance_field,
    segment_clearance_field,
)
from .dual_bounds import (
    ActionMaskBounds,
    PreparedDualBoundScope,
    ReferenceInclusionReport,
    RootBranchTube,
    SpatialCellPartition,
    TransitionLattice,
    aggregate_fine_action_mask_bounds,
    build_prepared_transition_lattice,
    build_spatial_cell_partition,
    check_fine_reference_inclusion,
    forward_reachable_tube,
    lift_coarse_action_masks,
    prepare_dual_bound_scope,
)
from .grid import axis, lane, movement_offsets, shift_from_source
from .legacy_forward import plan_legacy_forward_corridor
from .model import (
    AabbHazard,
    AabbTrajectoryHazard,
    AnnularSectorTrajectoryHazard,
    CorridorBounds,
    CorridorConfig,
    CorridorPlan,
    CorridorPoint,
    MovingAabbHazard,
    PiecewiseAabbHazard,
    RobustControlSpec,
    SegmentHazard,
    SegmentTrajectoryHazard,
)
from .prepared import PreparedCorridorProblem, prepare_corridor_problem
from .refinement_guides import build_policy_candidate_guide
from .refinement import LegacyFullFieldRefinement
from .robust import (
    RobustCorridorInduction,
    build_robust_corridor_induction,
)
from .rollout import rollout_robust_corridor

__all__ = [
    "AabbHazard",
    "AabbTrajectoryHazard",
    "AnnularSectorTrajectoryHazard",
    "ActionMaskBounds",
    "CorridorBounds",
    "CorridorConfig",
    "CorridorPlan",
    "CorridorPoint",
    "MovingAabbHazard",
    "PiecewiseAabbHazard",
    "PreparedDualBoundScope",
    "PreparedCorridorProblem",
    "QueryLocalDualBoundResult",
    "QueryLocalRefinementPatch",
    "ReferenceInclusionReport",
    "RootBranchTube",
    "LegacyFullFieldRefinement",
    "RobustCorridorInduction",
    "RobustControlSpec",
    "SegmentHazard",
    "SegmentTrajectoryHazard",
    "SpatialCellPartition",
    "TransitionLattice",
    "aabb_clearance_field",
    "aabb_clearance_volume",
    "aabb_sample_clearance_field",
    "annular_sector_clearance_field",
    "packed_annular_sector_clearance_field",
    "aggregate_fine_action_mask_bounds",
    "axis",
    "build_prepared_transition_lattice",
    "build_policy_candidate_guide",
    "build_query_local_refinement_patch",
    "build_spatial_cell_partition",
    "check_fine_reference_inclusion",
    "forward_reachable_tube",
    "clearance_field",
    "hazard_clearance_volume",
    "lane",
    "lift_coarse_action_masks",
    "movement_offsets",
    "packed_segment_clearance_field",
    "prepare_corridor_problem",
    "prepare_dual_bound_scope",
    "plan_legacy_forward_corridor",
    "build_robust_corridor_induction",
    "rollout_robust_corridor",
    "segment_clearance_field",
    "shift_from_source",
    "solve_query_local_dual_bounds",
    "solve_query_local_dual_bounds_vectorized",
    "trivial_coarse_action_bounds",
]
