"""TH08 live-controller composition and lifecycle boundaries."""

from .fresh_issue import (
    FreshEnemyIssueDependencies,
    FreshEnemyIssueResult,
    recertify_fresh_enemy_prefix,
)
from .issue_controller import InputDispatch, IssueController
from .iteration import (
    CapturedIteration,
    FreshIssueResult,
    PublishedGuidance,
    ServiceUpdate,
)
from .models import (
    Bullet,
    ENEMY_MAX_OBSERVED_WORLD_SPEED,
    EnemyBody,
    EnemyBodyModeMemory,
    EnemyPoolSnapshot,
    Item,
    PackedBulletSnapshot,
    SpellEnemyBodyGuard,
    serialize_bullet_trace,
    serialize_transform_record,
)
from .policy import (
    PolicyCoordinator,
    PolicyQueryRequest,
    PolicyQuerySnapshot,
    PrimaryPolicyQuery,
)
from .resources import LiveServiceResources
from .scene_clock import (
    AutoConfirmPulse,
    GameplaySceneGuard,
    INPUT_CLOCK_SHADOW_ROLE,
    SceneClockCoordinator,
    SceneGuardDecision,
    auto_confirm_eligible,
    frozen_auto_confirm_eligible,
    input_clock_message_key,
    semantic_clock_observation,
    serialize_semantic_clock_event,
    serialize_semantic_clock_observation,
)
from .sensor import (
    BULLET_POOL_BASE,
    BULLET_POOL_SIZE,
    BULLET_STRIDE,
    ITEM_MANAGER_BASE,
    ITEM_POOL_SIZE,
    ITEM_STRIDE,
    LASER_POOL_BASE,
    LASER_POOL_SIZE,
    LASER_STRIDE,
    RawPoolCapture,
    Sensor,
)
from .session import LiveSession
from .trace import TraceSink

__all__ = [
    "BULLET_POOL_BASE",
    "BULLET_POOL_SIZE",
    "BULLET_STRIDE",
    "AutoConfirmPulse",
    "Bullet",
    "CapturedIteration",
    "GameplaySceneGuard",
    "ENEMY_MAX_OBSERVED_WORLD_SPEED",
    "EnemyBody",
    "EnemyBodyModeMemory",
    "EnemyPoolSnapshot",
    "FreshEnemyIssueDependencies",
    "FreshEnemyIssueResult",
    "FreshIssueResult",
    "INPUT_CLOCK_SHADOW_ROLE",
    "ITEM_MANAGER_BASE",
    "ITEM_POOL_SIZE",
    "ITEM_STRIDE",
    "InputDispatch",
    "IssueController",
    "Item",
    "LASER_POOL_BASE",
    "LASER_POOL_SIZE",
    "LASER_STRIDE",
    "LiveServiceResources",
    "LiveSession",
    "PolicyCoordinator",
    "PolicyQueryRequest",
    "PolicyQuerySnapshot",
    "PackedBulletSnapshot",
    "PrimaryPolicyQuery",
    "PublishedGuidance",
    "RawPoolCapture",
    "SceneClockCoordinator",
    "SceneGuardDecision",
    "Sensor",
    "ServiceUpdate",
    "SpellEnemyBodyGuard",
    "TraceSink",
    "auto_confirm_eligible",
    "frozen_auto_confirm_eligible",
    "input_clock_message_key",
    "recertify_fresh_enemy_prefix",
    "semantic_clock_observation",
    "serialize_semantic_clock_event",
    "serialize_semantic_clock_observation",
    "serialize_bullet_trace",
    "serialize_transform_record",
]
