"""Constants for the bounded auxiliary-ECL event class."""

ECL_HEADER_SIZE = 12
ECL_OP_TERMINATE = 0x01
ECL_OP_JUMP = 0x04
ECL_OP_FIRST_DIRECT_FIRE = 0x60
ECL_OP_LAST_DIRECT_FIRE = 0x68
ECL_OP_DEFINE_BULLET_TRANSFORM = 0x6F
DIRECT_FIRE_ARGUMENT_SIZE = 32
TRANSFORM_ARGUMENT_SIZE = 28
MAXIMUM_TRANSFORM_INDEX = 17
NATIVE_DIRECT_TIMER_THRESHOLD = 0.99000001

PHYSICAL_TIMING_AVAILABLE = "available"
PHYSICAL_TIMING_UNAVAILABLE = "time_scale_unavailable"
PHYSICAL_TIMING_INVALID = "time_scale_invalid"
PHYSICAL_TIMING_BUDGET_EXHAUSTED = "physical_step_budget_exhausted"

STOP_HORIZON = "horizon"
STOP_TERMINATE = "terminate"
STOP_REPEATED_STATE = "repeated_state"
STOP_INSTRUCTION_LIMIT = "instruction_limit"
